---
title: "Synoptic Outlier Analysis"
author: "Bisrey Analytics"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE, warnings=FALSE }

# Purpose: To run hypothesis tests on indicator CO-03C to try and figure out how strong the evidence is that entities are over a target
# Author: Hans Aisake
# Date Created: December 2019
# Date Modified: see github
# Comments

#set WD, library and load packages
  libPath <-"H:/Hans/R Libraries"   #need to move into an execution R script
  .libPaths(libPath) #set the library path  #need to move into an execution R script
  wd <- "G:/VCHDecisionSupport/Patient Flow/Richmond RMarkdown Reports/Synoptic/SOW 2/20191221_TME_Analysis_SOW2"
 
   db_yml <- "G:/VCHDecisionSupport/Patient Flow/Richmond RMarkdown Reports/Synoptic/SOW 2/20191221_TME_Analysis_SOW2/CDRPROD.yml"
  setwd(wd) #set WD
  require("DescTools")
  require("DBI")
  require("tidyverse")
  require("DT")
  source("src.R", local = TRUE)

  
  #script parameters
  parameters <- 
    frame_data(
      ~IndicatorID, ~target, ~desiredDirection,  ~alpha, ~bc_average_2019, ~surgeon, ~pathologist,
      "'CO-03C'",   0.10, "A", 0.05, 0.07, TRUE, TRUE,
      "'BR-05A2'",  0.10, "B", 0.05, 0.08, TRUE, FALSE,
      "'BR-09'",    0.76, "A", 0.05, 0.76, TRUE, FALSE,
      "'CO-01A2'",  0.90, "B", 0.05, 0.88, TRUE, TRUE,
      "'CO-01B1'",  0.90, "B", 0.05, 0.85, TRUE, TRUE,
      "'CO-03D'",   0.90, "A", 0.05, 0.88, TRUE, TRUE,
      "'PR-04A'",   0.20, "A", 0.05, 0.25, TRUE, FALSE
    )

# load data from the database; you will need a yml file with the data source details
  query <- paste0("SELECT Tissue, Entity, EntityType, Timeframe, TimeFrameType, Numerator, Denominator, [Value], IndicatorID, NameIndicator FROM dbo.tblDashboardIndicators WHERE Interpolation_TimeFrame is null AND IndicatorID in (", paste(parameters$IndicatorID, collapse=","),") ")
  
  dw <- config::get("cdrprod",file = db_yml) #get dsn details from a config
  con <- DBI::dbConnect(odbc::odbc()
                        , Driver = dw$driver
                        , Server = dw$server
                        , Database =dw$database
                        , UID = dw$uid
                        , PWD = dw$pwd) #establish connection
  data <- dbGetQuery(con, query)   #run the query and get result
  dbDisconnect(con) #close data base connection
  df1.data <- as.data.frame(data) #turn data into a data frame

# for each indicator test the target
  test.results <- NULL #variable to hold test results
  
  for (ii in 1:nrow(parameters) ){
  
    # trouble shooting 
    # ii<-2
  
    #filter to the indicatorID
    id.loop <- gsub("'", "",parameters$IndicatorID[ii])  
    df2.loop <- df1.data %>% filter(IndicatorID == id.loop) 
    
    #build CI's and run tests
    ci <-BinomCI(df2.loop$Numerator
                 , df2.loop$Denominator
                 , conf.level =(1-parameters$alpha[ii])
                 , sides = "two.sided"
                 , method = "modified wilson")

    #get pvalues for tests of all entities
    p.val <- mapply(test, df2.loop$Numerator
                        , df2.loop$Denominator
                        , parameters$target[ii] #parameters$bc_average_2019[ii]
                        , parameters$desiredDirection[ii]
                        , parameters$alpha[ii]) 
    
    label_columns <- c("IndicatorID"
                       ,"Tissue"
                        ,"NameIndicator"
                        ,"Entity"
                        ,"EntityType"
                        ,"Timeframe"
                        ,"Value"
                        ,"Denominator")
    labs <- df2.loop[,label_columns ] #labels for the pvalues

    #store results
    x <- data.frame(labs
                    , target = rep( parameters$target[ii], nrow(labs))
                    , p.val
                    , lwr.ci=as.numeric(ci[, c("lwr.ci")])
                    , upr.ci=as.numeric(ci[, c("upr.ci")]) #put results into a final data set
                    , alpha = rep( parameters$alpha[ii], nrow(labs)))
    x$reject <- (x$p.val <= x$alpha)
    test.results <- rbind(x, test.results) 
    #itterate to next indicator
  }
  
  # going to display the significant results in a graph colour = significant
  write.csv(file="test_target.csv", x=test.results, append=FALSE)
  #write.csv(file="test_bc_avg.csv", x=test.results)
  
  # we may still want funnel plots and determination of high/low performance regions using the funnel plot.
  # may change the parameter target to BC average
  
```

## Results

The results of bionomial testing

```{r testResults, echo=FALSE, warnings=FALSE, include=TRUE}

 test.results %>%
    sample_n(10) %>%
    arrange(desc(p.val), desc(Timeframe) ) %>% 
    datatable(extensions = 'Buttons',
              options = list(dom = 'Bfrtip', 
                             buttons = c("excel")))

```

FIN
